package dbconstants;

public class LoginDBConstants {
public static final String USER_PROFILE_ID="UserProfileId";
public static final String COMPANY_ID="CompanyId";
public static final String COMPANY_CODE="CompanyCode";
public static final String COMPANY_NAME="CompanyName";
public static final String CONNECTION_ID="ConnectionId";
public static final String IS_CONNECTED_TO_MAIL_CHIMP_ACCOUNT="IsConnectedToMailChimpAccount";
public static final String MAIL_CHIMP_ACCOUNT_EMAIL="MailChimpAccountEmail";
public static final String EMAIL_INTEGRATION_ID="EmailIntegrationId";
public static final String ALTERNATIVE_EMAIL_ADDRESS="AlternativeEmailAddress";
public static final String IS_MY_LINKED_EMAIL_SHARED="IsMyLinkedEmailsShared";
public static final String IS_MY_EMAIL_CONVERSATION_PRIVATE="IsMyEmailConversationsPrivate";
public static final String IS_MY_LINK_MY_EMAIL_MANUALLY="IsLinkMyEmailManually";
public static final String IS_EMAIL_LINK_WITH_DEALS="IsEmailLinkWithDeals";
public static final String CONTACT_ID="ContactId";
public static final String IS_CONNECTED_TO_GOOGLE_ACCOUNT="IsConnectedToGoogleAccount";
public static final String GOOGLE_ACCOUNT_EMAIL="GoogleAccountEmail";
public static final String DRIVE_ID="DriveId";
public static final String PROFILE_PICTURE_ID="ProfilePictureId";
public static final String ATTACHMENT_ID="AttachmentId";
public static final String REMINDER_EMAIL_ID="ReminderEmailId";
public static final String REMINDER_TYPE_ID="ReminderTypeId";
public static final String REMINDER_TIME_ID="ReminderTimeId";
public static final String USER_INTERFACE_ID="UserInterfaceId";
public static final String IS_DEAL="IsDeal";
public static final String IS_PERSON="IsPerson";
public static final String IS_ORGANIZATION="IsOrganization";
public static final String TIME_ZONE="TimeZone";
public static final String USER_LOCALE_ID="UserLocaleId";
public static final String LANGUAGE_ID="LanguageId";
public static final String CURRENCY_ID="CurrencyId";
public static final String IS_ACTIVE="IsActive";
public static final String CREATED_DATE="CreatedDate";
public static final String MODIFIED_DATE="ModifiedDate";
public static final String HAS_PIC="HasPic";
public static final String REGISTRATION_ID="RegistrationId";
public static final String EMAIL_ADDRESS="EmailAddress";
public static final String USER_PASSWORD="UserPassword";
public static final String USER_NAME="UserName";
public static final String INDUSTRY_TYPE_ID="IndustryTypeId";
public static final String LAST_LOGIN="LastLoginOn";
}
